substitutions:
  _PROJECT_ID: pr-manualdeployment

steps:
  - name: 'gcr.io/cloud-builders/docker'
  #  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-test/my-image-test', '.'] #TEST
  #  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-prod/my-image-prod', '.'] #PROD
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-dev/my-image-dev', '.'] #DEV
  - name: 'gcr.io/cloud-builders/docker' 
  #  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-test/my-image-test'] #TEST
  #  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-prod/my-image-prod'] #PROD
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-dev/my-image-dev'] #DEV
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=gke.yaml
    #- --image=us-central1-docker.pkg.dev/pr-manualdeployment/my-repo/my-image-test #TEST
    #- --image=us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-prod/my-image-prod #PROD
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-dev/my-image-dev #DEV
    - --location=us-central1-c
    #- --cluster=gcp-devops-project #TEST
    #- --cluster=gcp-devops-prod #PROD
    - --cluster=gcp-devops-dev #DEV
    #- --namespace=gcp-devops-test #TEST
    #- --namespace=gcp-devops-prod #PROD
    - --namespace=gcp-devops-dev #DEV