---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gcp-devops-gke"
  #namespace: "gcp-devops-test" #TEST
  #namespace: "gcp-devops-prod" #PROD
  namespace: "gcp-devops-dev" #DEV
  labels:
    app: "gcp-gke-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gcp-gke-app"
  template:
    metadata:
      labels:
        app: "gcp-gke-app"
    spec:
      containers:
      - name: "my-image-1"
        image: "us-central1-docker.pkg.dev/pr-manualdeployment/my-repo/my-image:latest" #TEST
        #image: "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-prod/my-image-prod:latest" #PROD
        #image: "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo-dev/my-image-dev:latest" #DEV
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "gcp-devops-gke-hpa-87vz"
  #namespace: "gcp-devops-prod" #PROD
  #namespace: "gcp-devops-test" #TEST
  namespace: "gcp-devops-dev" #DEV
  labels:
    app: "gcp-gke-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "gcp-devops-gke"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-devops-gke"
  #namespace: "gcp-devops-prod" #PROD
  #namespace: "gcp-devops-test" #TEST
  namespace: "gcp-devops-dev" #DEV  
  labels:
    app: "gcp-gke-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp-gke-app"
  type: "LoadBalancer"
---